window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\AVTJH2744\\AppData\\Roaming",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-A1CKVUT",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "dp0": "D:\\ubuntu\\osb-ui\\osb-sdk-ui\\node_modules\\.bin\\",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "HOME": "C:\\Users\\AVTJH2744",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\AVTJH2744",
  "INIT_CWD": "D:\\ubuntu\\osb-ui\\osb-sdk-ui",
  "JAVA_HOME": "C:\\Program Files\\Java\\jdk1.8.0_301",
  "LOCALAPPDATA": "C:\\Users\\AVTJH2744\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-A1CKVUT",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_config_access": "",
  "npm_config_allow_same_version": "",
  "npm_config_also": "",
  "npm_config_always_auth": "",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"build\"],\"original\":[\"run\",\"build\"]}",
  "npm_config_audit": "true",
  "npm_config_audit_level": "low",
  "npm_config_auth_type": "legacy",
  "npm_config_before": "",
  "npm_config_bin_links": "true",
  "npm_config_browser": "",
  "npm_config_ca": "",
  "npm_config_cache": "C:\\Users\\AVTJH2744\\AppData\\Roaming\\npm-cache",
  "npm_config_cache_lock_retries": "10",
  "npm_config_cache_lock_stale": "60000",
  "npm_config_cache_lock_wait": "10000",
  "npm_config_cache_max": "Infinity",
  "npm_config_cache_min": "10",
  "npm_config_cafile": "",
  "npm_config_cert": "",
  "npm_config_cidr": "",
  "npm_config_color": "true",
  "npm_config_commit_hooks": "true",
  "npm_config_depth": "Infinity",
  "npm_config_description": "true",
  "npm_config_dev": "",
  "npm_config_dry_run": "",
  "npm_config_editor": "notepad.exe",
  "npm_config_engine_strict": "",
  "npm_config_fetch_retries": "2",
  "npm_config_fetch_retry_factor": "10",
  "npm_config_fetch_retry_maxtimeout": "60000",
  "npm_config_fetch_retry_mintimeout": "10000",
  "npm_config_force": "",
  "npm_config_format_package_lock": "true",
  "npm_config_fund": "true",
  "npm_config_git": "git",
  "npm_config_git_tag_version": "true",
  "npm_config_global": "",
  "npm_config_globalconfig": "C:\\Program Files\\nodejs\\etc\\npmrc",
  "npm_config_globalignorefile": "C:\\Program Files\\nodejs\\etc\\npmignore",
  "npm_config_global_style": "",
  "npm_config_group": "",
  "npm_config_ham_it_up": "",
  "npm_config_heading": "npm",
  "npm_config_https_proxy": "",
  "npm_config_if_present": "",
  "npm_config_ignore_prepublish": "",
  "npm_config_ignore_scripts": "",
  "npm_config_init_author_email": "",
  "npm_config_init_author_name": "",
  "npm_config_init_author_url": "",
  "npm_config_init_license": "ISC",
  "npm_config_init_module": "C:\\Users\\AVTJH2744\\.npm-init.js",
  "npm_config_init_version": "1.0.0",
  "npm_config_json": "",
  "npm_config_key": "",
  "npm_config_legacy_bundling": "",
  "npm_config_link": "",
  "npm_config_local_address": "",
  "npm_config_loglevel": "notice",
  "npm_config_logs_max": "10",
  "npm_config_long": "",
  "npm_config_maxsockets": "50",
  "npm_config_message": "%s",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Users\\AVTJH2744\\AppData\\Roaming\\nvm\\v14.17.3\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_node_options": "",
  "npm_config_node_version": "14.17.3",
  "npm_config_noproxy": "",
  "npm_config_offline": "",
  "npm_config_onload_script": "",
  "npm_config_only": "",
  "npm_config_optional": "true",
  "npm_config_otp": "",
  "npm_config_package_lock": "true",
  "npm_config_package_lock_only": "",
  "npm_config_parseable": "",
  "npm_config_prefer_offline": "",
  "npm_config_prefer_online": "",
  "npm_config_prefix": "C:\\Program Files\\nodejs",
  "npm_config_preid": "",
  "npm_config_production": "",
  "npm_config_progress": "true",
  "npm_config_proxy": "",
  "npm_config_read_only": "",
  "npm_config_rebuild_bundle": "true",
  "npm_config_registry": "https://registry.npmjs.org/",
  "npm_config_rollback": "true",
  "npm_config_save": "true",
  "npm_config_save_bundle": "",
  "npm_config_save_dev": "",
  "npm_config_save_exact": "",
  "npm_config_save_optional": "",
  "npm_config_save_prefix": "^",
  "npm_config_save_prod": "",
  "npm_config_scope": "",
  "npm_config_scripts_prepend_node_path": "warn-only",
  "npm_config_script_shell": "",
  "npm_config_searchexclude": "",
  "npm_config_searchlimit": "20",
  "npm_config_searchopts": "",
  "npm_config_searchstaleness": "900",
  "npm_config_send_metrics": "",
  "npm_config_shell": "C:\\Windows\\system32\\cmd.exe",
  "npm_config_shrinkwrap": "true",
  "npm_config_sign_git_commit": "",
  "npm_config_sign_git_tag": "",
  "npm_config_sso_poll_frequency": "500",
  "npm_config_sso_type": "oauth",
  "npm_config_strict_ssl": "true",
  "npm_config_tag": "latest",
  "npm_config_tag_version_prefix": "v",
  "npm_config_timing": "",
  "npm_config_tmp": "C:\\Users\\AVTJH2~1\\AppData\\Local\\Temp",
  "npm_config_umask": "0000",
  "npm_config_unicode": "",
  "npm_config_unsafe_perm": "true",
  "npm_config_update_notifier": "true",
  "npm_config_usage": "",
  "npm_config_user": "",
  "npm_config_userconfig": "C:\\Users\\AVTJH2744\\.npmrc",
  "npm_config_user_agent": "npm/6.14.13 node/v14.17.3 win32 x64",
  "npm_config_version": "",
  "npm_config_versions": "",
  "npm_config_viewer": "browser",
  "npm_execpath": "C:\\Users\\AVTJH2744\\AppData\\Roaming\\nvm\\v14.17.3\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_package_dependencies_base_64": "^1.0.0",
  "npm_package_dependencies_carbon_components": "^10.46.0",
  "npm_package_dependencies_carbon_components_react": "^7.46.0",
  "npm_package_dependencies_carbon_icons": "^7.0.7",
  "npm_package_dependencies_dotenv": "^10.0.0",
  "npm_package_dependencies_lodash": "^4.17.21",
  "npm_package_dependencies_node_sass": "^6.0.1",
  "npm_package_dependencies_react": "^17.0.2",
  "npm_package_dependencies_react_dom": "^17.0.2",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "npm_package_dependencies_react_router_dom": "^5.3.0",
  "npm_package_dependencies_react_scripts": "4.0.3",
  "npm_package_dependencies_sass": "^1.43.2",
  "npm_package_dependencies_serve": "^12.0.1",
  "npm_package_dependencies_web_vitals": "^1.1.2",
  "npm_package_dependencies__carbon_colors": "^10.33.0",
  "npm_package_dependencies__carbon_grid": "^10.38.0",
  "npm_package_dependencies__carbon_themes": "^10.45.0",
  "npm_package_dependencies__testing_library_jest_dom": "^5.14.1",
  "npm_package_dependencies__testing_library_react": "^11.2.7",
  "npm_package_dependencies__testing_library_user_event": "^12.8.3",
  "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_gitHead": "f82320fbfd327f9451b41460d0c46ca0915ec1ff",
  "npm_package_name": "osb-broker-ui",
  "npm_package_private": "true",
  "npm_package_readmeFilename": "README.md",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_eject": "react-dotenv && react-scripts eject",
  "npm_package_scripts_serve": "react-dotenv && serve -s build -l 3001",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_package_scripts_test": "react-dotenv && react-scripts test",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "NVM_HOME": "C:\\Users\\AVTJH2744\\AppData\\Roaming\\nvm",
  "NVM_SYMLINK": "C:\\Program Files\\nodejs",
  "OneDrive": "C:\\Users\\AVTJH2744\\OneDrive",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\AVTJH2744\\AppData\\Roaming\\nvm\\v14.17.3\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;D:\\ubuntu\\osb-ui\\osb-sdk-ui\\node_modules\\.bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Users\\AVTJH2744\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Cloud Foundry;C:\\Program Files\\Java\\jdk1.8.0_301\\bin;C:\\apache-maven-3.8.2\\bin;C:\\php;;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Users\\AVTJH2744\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\AVTJH2744\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Users\\AVTJH2744\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\AVTJH2744\\AppData\\Local\\Programs\\Microsoft VS Code\\bin",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 12, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e0c",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "%ProgramFiles%\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\AVTJH2~1\\AppData\\Local\\Temp",
  "TMP": "C:\\Users\\AVTJH2~1\\AppData\\Local\\Temp",
  "USERDNSDOMAIN": "gmx.ibm.com",
  "USERDOMAIN": "GMX",
  "USERDOMAIN_ROAMINGPROFILE": "GMX",
  "USERNAME": "AVTJH2744",
  "USERPROFILE": "C:\\Users\\AVTJH2744",
  "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
  "windir": "C:\\Windows",
  "WSLENV": "WT_SESSION::WT_PROFILE_ID",
  "WT_PROFILE_ID": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
  "WT_SESSION": "0a4b464f-e294-4d13-aadf-261e3f737917",
  "ZES_ENABLE_SYSMAN": "1",
  "_prog": "node"
};