# This is a basic workflow to help you get started with Actions

name: deploy-ce

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploymentApiKey:
        description: 'Deployment ApiKey'     
        required: true
        default: 'your apikey'
      onboardingApiKey:
        description: 'Onboarding ApiKey'     
        required: true
        default: 'your apikey'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_IAM_API_KEY: ${{ github.event.inputs.deploymentApiKey }}
      ONBOARDING_ENV: ${{ github.event.inputs.onboardingApiKey }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Populate environemnt
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          export $(cat deploy/build.config.properties)
          export $(cat deploy/ce/ce.config.properties)
          make build
          made deploy-ce
        

