# This is a basic workflow to help you get started with Actions

name: deploy-ce

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_IAM_API_KEY: ${{ secrets.DEPLOYMENT_IAM_API_KEY }}
      ONBOARDING_ENV: ${{ secrets.ONBOARDING_ENV }}
      GC_OBJECT_ID: e4bb27d5-17b7-450d-af58-ae3e20c4aa93

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Populate environemnt
        run: |
          export $(cat deploy/build.config.properties)
          export $(cat deploy/ce/ce.config.properties)
          echo "gc object id: ${GC_OBJECT_ID} ${DEPLOYMENT_IAM_API_KEY} ${ONBOARDING_ENV}"
          make build
          made deploy-ce
        

