# This is a basic workflow to help you get started with Actions

name: Create and Deploy an Open Service Broker

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_IAM_API_KEY: ${{ secrets.DEPLOYMENT_IAM_API_KEY }}
      ONBOARDING_IAM_API_KEY: ${{ secrets.ONBOARDING_IAM_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build and deploy to Code Engine
        run: |
          export $(cat deploy/build.config.properties)
          export $(cat deploy/ce/ce.config.properties)
          make build-deploy-ce


